# Generated by Django 3.0.7 on 2020-06-17 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_world_daily'),
    ]

    operations = [
        migrations.CreateModel(
            name='kr_region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kr_date', models.CharField(max_length=200)),
                ('kr_region', models.CharField(max_length=200)),
                ('kr_confirmed', models.CharField(max_length=200)),
                ('kr_death', models.CharField(max_length=200)),
                ('kr_released', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='world_daily',
            name='world_confirmed',
        ),
        migrations.RemoveField(
            model_name='world_daily',
            name='world_confirmed_change',
        ),
        migrations.RemoveField(
            model_name='world_daily',
            name='world_date',
        ),
        migrations.RemoveField(
            model_name='world_daily',
            name='world_death',
        ),
        migrations.RemoveField(
            model_name='world_daily',
            name='world_death_change',
        ),
        migrations.AddField(
            model_name='world_daily',
            name='world_deaths_rate',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='world_daily',
            name='world_new_cases',
            field=models.CharField(default=2, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='world_daily',
            name='world_new_death',
            field=models.CharField(default=5, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='world_daily',
            name='world_today_date',
            field=models.CharField(default=5, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='world_daily',
            name='world_total_confirmed',
            field=models.CharField(default=5, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='world_daily',
            name='world_total_death',
            field=models.CharField(default=5, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='world_daily',
            name='world_country',
            field=models.CharField(max_length=20),
        ),
    ]
