# Generated by Django 3.0.7 on 2020-06-19 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20200618_0259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='krdaily',
            name='kr_candidate',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='krdaily',
            name='kr_confirmed',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='krdaily',
            name='kr_date',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='krdaily',
            name='kr_death',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='krdaily',
            name='kr_negative',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='krdaily',
            name='kr_released',
            field=models.CharField(max_length=20),
        ),
    ]
